language: generic 
sudo: required
services:
  - docker
before_install:
  - docker build -t danielpbarros/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true danielpbarros/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-sa-east-1-957003135258"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY